---
# YAML documents begin with the document separator ---

# Le tiret en YAML indique une Liste
# Un playbook Ansible contient une liste de plays
- name: Configuration du message du jour
  hosts: centos
  user: root
  gather_facts: false

  # Play: la configuration générale du play

  # Vars: variables qui s'appliquent au play
  vars:
    motd: "Bienvenue sur CentOS (powered by Ansible) !!!\n"

  # Tasks: La liste des tâches à exécuter
  tasks:
    - name: Configure le motd
      copy: # On utilise le module copy
        content: "{{ motd }}"
        dest: /etc/motd
      notify: MOTD changed

  # Handlers: la liste des handlers à utilisé en réaction à un notify_key
  handlers:
    - name: MOTD changed
      debug:
        msg: Le MOTD a été changé

  # Roles: les roles à importer dans le play

# Three dots indicate the end of a YAML document
...
