---
# YAML documents begin with the document separator ---

# Le tiret en YAML indique une Liste
# Un playbook Ansible contient une liste de plays
- name: Jinja2
  hosts: ubuntu-c

  # Play: la configuration générale du play

  # Vars: variables qui s'appliquent au play

  # Tasks: La liste des tâches à exécuter
  tasks:
    - name: Jinja2 range
      debug:
        msg: > # En jinja2, la dernière valeur de la range est ignorée
              {% for entry in range(1,11) -%}
                {{ entry }}
              {% endfor -%}

  # Handlers: la liste des handlers à utilisé en réaction à un notify_key

  # Roles: les roles à importer dans le play

# Three dots indicate the end of a YAML document
...
