---
# YAML documents begin with the document separator ---

# Le tiret en YAML indique une Liste
# Un playbook Ansible contient une liste de plays
- name: Variables
  hosts: centos
  gather_facts: true

  # Play: la configuration générale du play

  # Vars: variables qui s'appliquent au play

  # Tasks: La liste des tâches à exécuter
  tasks:
    - name: Show value
      debug:
        "{{ ansible_default_ipv4.address }}"

  # Handlers: la liste des handlers à utilisé en réaction à un notify_key

  # Roles: les roles à importer dans le play

# Three dots indicate the end of a YAML document
...
